server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  cloud:
    stream:
      kafka:
        binder:
          brokers: velomobile-01.srvs.cloudkafka.com:9094, velomobile-02.srvs.cloudkafka.com:9094, velomobile-03.srvs.cloudkafka.com:9094
          configuration:
            security.protocol: SASL_SSL
            sasl:
              mechanism: SCRAM-SHA-256
              jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="iwiyz2ep" password="AUnRE42ufiOYRWCHWQ6H3pcWSng-3YZQ";
      bindings:
        output:
          destination: iwiyz2ep-order

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"